{% set name = "flask-restplus" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fad697e1d91dfc13c078abcb86003f438a751c5a4ff41b84c9050199d2eab62

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask >=0.8
    - six >=1.3.0
    - jsonschema
    - pytz
    - aniso8601 >=0.82
    - enum34  # [py2k]
 
test:
  imports:
    - flask_restplus
  commands:
    - test -f "${SP_DIR}/{{ name.replace('-', '_') }}/static/swagger-ui.js"      # [unix]
    - test -f "${SP_DIR}/{{ name.replace('-', '_') }}/static/swagger-ui.css"      # [unix]
    - if not exist %SP_DIR%\\{{ name.replace('-', '_') }}\\static\\swagger-ui.js exit 1  # [win]
    - if not exist %SP_DIR%\\{{ name.replace('-', '_') }}\\static\\swagger-ui.css exit 1  # [win]

about:
  home: https://github.com/noirbizarre/flask-restplus
  license: MIT
  license_family: MIT
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'Fully featured framework for fast, easy and documented API development with Flask'

  description: |
    Flask-RESTPlus is an extension for Flask that adds support for quickly
    building REST APIs. Flask-RESTPlus encourages best practices with minimal
    setup. If you are familiar with Flask, Flask-RESTPlus should be easy to
    pick up. It provides a coherent collection of decorators and tools to
    describe your API and expose its documentation properly using Swagger.
  doc_url: http://flask-restplus.readthedocs.org/
  dev_url: https://github.com/noirbizarre/flask-restplus

extra:
  recipe-maintainers:
    - frol
