{% set name = "flask-restplus" %}
{% set version = "0.10.1" %}
{% set sha256 = "129767ba6087a6f0a6d1bd901f4c11192b4d33fe80c38cf2a8a0b5f8dd6049e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - flask >=0.8
    - six >=1.3.0
    - jsonschema
    - pytz
    - aniso8601 >=0.82
 
test:
  imports:
    - flask_restplus

about:
  home: https://github.com/noirbizarre/flask-restplus
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fully featured framework for fast, easy and documented API development with Flask'

  description: |
    Flask-RESTPlus is an extension for Flask that adds support for quickly
    building REST APIs. Flask-RESTPlus encourages best practices with minimal
    setup. If you are familiar with Flask, Flask-RESTPlus should be easy to
    pick up. It provides a coherent collection of decorators and tools to
    describe your API and expose its documentation properly using Swagger.
  doc_url: http://flask-restplus.readthedocs.org/
  dev_url: https://github.com/noirbizarre/flask-restplus

extra:
  recipe-maintainers:
    - frol
