{% set name = "flask-restplus" %}
{% set version = "0.11.0" %}
{% set sha256 = "e7f07a8df28406e55b6997e3cebe28519feea42b2af618eb67be7e660de8019d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/noirbizarre/flask-restplus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - flask >=0.8
    - six >=1.3.0
    - jsonschema
    - pytz
    - aniso8601 >=0.82
    - enum34  # [py2k]
 
test:
  imports:
    - flask_restplus

about:
  home: https://github.com/noirbizarre/flask-restplus
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fully featured framework for fast, easy and documented API development with Flask'

  description: |
    Flask-RESTPlus is an extension for Flask that adds support for quickly
    building REST APIs. Flask-RESTPlus encourages best practices with minimal
    setup. If you are familiar with Flask, Flask-RESTPlus should be easy to
    pick up. It provides a coherent collection of decorators and tools to
    describe your API and expose its documentation properly using Swagger.
  doc_url: http://flask-restplus.readthedocs.org/
  dev_url: https://github.com/noirbizarre/flask-restplus

extra:
  recipe-maintainers:
    - frol
