appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lbygQQ5+Kfo0OxgXQYPeE+a+9I3eu1cD6j8kKojZAhclwtlD2+Xd4MYW0tRqYw1scqxC6TdPipub73+UWFpWEVvgUIHBvSFK5I0DWmo36BrfSI01zO+dhCjTCKhlHZ7zgHuP/mjVHfPMnnysj/ukYvr2iSQUZHZUy42FUWpxevCu3j58Tbu4XvcwDDfGZwhj/E4J+cmuKoh2iPkQbBqNsRGtKLEzF5Au+505vPIy/qP5tKqeCCiETSZdzuNrU6zffPVUa7hQj/yTfjtI+C+n6/cX0Nmh7tXkKjQkR641eTyeSeCX99laBxy64tXm6LJmWBZh7cp4QHlGpLwCDEzuLwqA5GSl2NWWQ+9wwEM8mNY7B0NgcB/Hj4j4HhkT4hZgvZsn9YuC3quZG1p8ccwhgBNAUjKiDLtvUqsR354JBoKTXl1pyhG4AekRuUH9SyrXlrI+DRJ6jhEYvlg4dp0XxCyQoCd+T4lPs4p7BlLBHxdS55taq8UkxJNPN476dXEQRVcRNkWVtf0C6zCzerVdmweJdozp2nrlz1Q1MHF6XrIGT7car9zXxte0NFySZ4zLgYMcRDIeIxbiIIOUHVNREma4xqZS7K6XnBLgC4OGlpOJ+MBXaLmxe2IJsn9cbmc2ghjMc5NVVsQk+nqfxTuSgu02guNoWw/AGSgeYwlk7mY=}
provider:
  win: azure
  linux_ppc64le: default
conda_forge_output_validation: true
